spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/analysed?useSSL=false&serverTimezone=UTC
    username: root
    password: hyxiao
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false
  #  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  redis:
    host: localhost
    port: 6379

  logging:
    level:
      root: INFO
      com.xiaohub: DEBUG